name: ERP_env
channels:
  - defaults
dependencies:
  - python==3.11
  - anaconda
  - numpy
  - scipy==1.11.3
  - pandas
  - matplotlib==3.8.0
  - pip
  - pip:
    - mne==1.5.1
    - datetime
    - pyyaml
    - screeninfo